# Generated by Django 3.2.8 on 2023-05-01 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=50)),
                ('gst', models.CharField(default='', max_length=15)),
                ('is_agent', models.BooleanField(default='false')),
                ('is_party', models.BooleanField(default='false')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(default='', max_length=50)),
                ('quantity', models.CharField(default='', max_length=50)),
                ('metrics', models.CharField(default='', max_length=50)),
                ('rate', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('agent2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent2', to='app1.users')),
                ('e_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_from', to='app1.users')),
                ('e_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_to', to='app1.users')),
            ],
        ),
    ]
