# Generated by Django 3.2.8 on 2023-05-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=50)),
                ('gst', models.CharField(default='', max_length=15)),
                ('remaining_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=50)),
                ('gst', models.CharField(default='', max_length=15)),
                ('remaining_balance', models.IntegerField(default=0)),
                ('outstanding_brokerage', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_agent',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_party',
        ),
        migrations.AddField(
            model_name='entry',
            name='brokerage_amount_buyer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='brokerage_amount_seller',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='brokerage_buyer_clear_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='brokerage_seller_clear_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='clear_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='interest_d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='outstanding_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='agent2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent2', to='app1.agent'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='e_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_from', to='app1.party'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='e_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_to', to='app1.party'),
        ),
    ]
